name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Erlang
      uses: erlef/setup-beam@v1
      with:
        otp-version: '25'
        gleam-version: '1.5.1'
        rebar3-version: '3.22.1'

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          _build
          deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/gleam.toml') }}
        restore-keys: |
          ${{ runner.os }}-mix-

    - name: Install dependencies
      run: gleam deps download

    - name: Run build
      run: gleam run build

    - name: Run tests
      run: gleam test
      